# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tasks.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'tasks.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btasks.proto\x12\x05tasks\"\x07\n\x05\x45mpty\"4\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x11\n\tcompleted\x18\x03 \x01(\x08\"&\n\x08TaskList\x12\x1a\n\x05tasks\x18\x01 \x03(\x0b\x32\x0b.tasks.Task\"\x1b\n\rTaskIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"5\n\x11\x43reateTaskRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x11\n\tcompleted\x18\x02 \x01(\x08\"c\n\x11UpdateTaskRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\x05title\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x16\n\tcompleted\x18\x03 \x01(\x08H\x01\x88\x01\x01\x42\x08\n\x06_titleB\x0c\n\n_completed\"8\n\x0cTaskResponse\x12\x19\n\x04task\x18\x01 \x01(\x0b\x32\x0b.tasks.Task\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"4\n\x12\x44\x65leteTaskResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\xa7\x02\n\x0bTaskService\x12)\n\x08GetTasks\x12\x0c.tasks.Empty\x1a\x0f.tasks.TaskList\x12\x34\n\x07GetTask\x12\x14.tasks.TaskIdRequest\x1a\x13.tasks.TaskResponse\x12;\n\nCreateTask\x12\x18.tasks.CreateTaskRequest\x1a\x13.tasks.TaskResponse\x12;\n\nUpdateTask\x12\x18.tasks.UpdateTaskRequest\x1a\x13.tasks.TaskResponse\x12=\n\nDeleteTask\x12\x14.tasks.TaskIdRequest\x1a\x19.tasks.DeleteTaskResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tasks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=22
  _globals['_EMPTY']._serialized_end=29
  _globals['_TASK']._serialized_start=31
  _globals['_TASK']._serialized_end=83
  _globals['_TASKLIST']._serialized_start=85
  _globals['_TASKLIST']._serialized_end=123
  _globals['_TASKIDREQUEST']._serialized_start=125
  _globals['_TASKIDREQUEST']._serialized_end=152
  _globals['_CREATETASKREQUEST']._serialized_start=154
  _globals['_CREATETASKREQUEST']._serialized_end=207
  _globals['_UPDATETASKREQUEST']._serialized_start=209
  _globals['_UPDATETASKREQUEST']._serialized_end=308
  _globals['_TASKRESPONSE']._serialized_start=310
  _globals['_TASKRESPONSE']._serialized_end=366
  _globals['_DELETETASKRESPONSE']._serialized_start=368
  _globals['_DELETETASKRESPONSE']._serialized_end=420
  _globals['_TASKSERVICE']._serialized_start=423
  _globals['_TASKSERVICE']._serialized_end=718
# @@protoc_insertion_point(module_scope)
